---
# tasks/inventory.yml - GET calls to inventory endpoint

- name: Set inventory API URL
  ansible.builtin.set_fact:
    api_endpoint_url: "{{ semaphore_api_base_url }}/project/{{ semaphore_project_id }}/inventory{% if semaphore_resource_id != '' and semaphore_resource_id != None %}/{{ semaphore_resource_id }}{% endif %}"
    api_endpoint_name: "inventory"
    api_response_var: "semaphore_inventory_data"

- name: Execute API call for inventory
  ansible.builtin.include_tasks: common_api_call.yml
