---
# tasks/keys.yml - GET calls to keys endpoint

- name: Set keys API URL
  ansible.builtin.set_fact:
    api_endpoint_url: "{{ semaphore_api_base_url }}/project/{{ semaphore_project_id }}/keys{% if semaphore_resource_id != '' and semaphore_resource_id != None %}/{{ semaphore_resource_id }}{% endif %}"
    api_endpoint_name: "keys"
    api_response_var: "semaphore_keys_data"

- name: Execute API call for keys
  ansible.builtin.include_tasks: common_api_call.yml
