---
# tasks/templates.yml - GET calls to templates endpoint

- name: Set templates API URL
  ansible.builtin.set_fact:
    api_endpoint_url: "{{ semaphore_api_base_url }}/project/{{ semaphore_project_id }}/templates{% if semaphore_resource_id != '' and semaphore_resource_id != None %}/{{ semaphore_resource_id }}{% endif %}"
    api_endpoint_name: "templates"
    api_response_var: "semaphore_templates_data"

- name: Execute API call for templates
  ansible.builtin.include_tasks: common_api_call.yml
