---
# create_semaphore.yaml - Deploy Semaphore UI using the semaphore_ui role
#
# Usage:
#   ansible-playbook playbooks/create_semaphore.yaml -e semaphore_admin_password=YourSecurePassword123

- name: Deploy Semaphore UI
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - role: semaphore_ui
      vars:
        semaphore_api_token_vault_file: "{{ playbook_dir }}/../secrets/vault.yml"
        semaphore_vault_password_file: "{{ playbook_dir }}/../secrets/.vault_pass"
